title: Aris Wells # your name (or website title) here
logo: "/images/Aris DSC_9832s.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my digital portfolio! 
  <br><br>
  My name is Aris Wells and I am a spring 2022 graduate of the Master of Science in Information Studies (MSIS) program at the University of Texas at Austin. I earned my Bachelor of Sciences in Physics from Southwestern University.
  <br><br>
  The program has exposed to be several different ways information can be formatted and presented to improve the functionality of applications and inform decision making and the following projects are just a sample of those.

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
